export const FETCHING_MOVIES = "FETCHING_MOVIES";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";
export const FETCH_MORE_MOVIES = "FETCH_MORE_MOVIES";

export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_FAILED = "FETCH_DETAIL_FAILED";
